server:
  port: 8082
spring:
  application:
    name: transaction-service
  datasource:
    url: jdbc:postgresql://localhost:5433/mybankdb
    username: devadmin
    password: devadmin123pass

---
server:
  port: 8080
spring:
  config:
    activate:
      on-profile: docker
  datasource:
    url: jdbc:postgresql://postgres:5432/mybankdb
    username: devadmin
    password: devadmin123pass